### ISSUE TITLE
Undefined property: WC_dokuonecheckout_Gateway::$prefixid

### ISSUE THREAD

**Issue by arixwap** [PTNUSASATUINTIARTHA-DOKU/Plugin-DOKU-Woocomerce#1]
Hello team Doku, 

I run some WooCommerce and use this plugin. But suddenly, I got some error after installed this plugin.
It says **`Undefined property: WC_dokuonecheckout_Gateway::$prefixid`** on file **`dokuonecheckout.php:145 `**

![Screenshot 2020-11-23 at 12 07 58 PM](https://user-images.githubusercontent.com/11769214/99928561-8e398780-2d84-11eb-9962-e0dc496dc9f1.JPG)

https://github.com/PTNUSASATUINTIARTHA-DOKU/Plugin-DOKU-Woocomerce/blob/572cde7546296b45e8bd8911357d7af870dda79e/dokuonecheckout.php#L145

Is this okay if we still run site with this error? or should we fix it? If so, I can help with that.
**Thanks before**

**Comment by mirzaditaardani** [comment]
hi @arixwap, thank you for reporting this issue.

can u please let us know more detail information (WooCommerce versiont, etc)?
is your installation successfully installed ?

**Comment by arixwap** [comment]
Sure,
WooCommerce version: |   | 4.7.0
WordPress version: |   | 5.5.3

Btw, I already fix this error on my site, can I send a pull request to this repo?

**Comment by ariefrizkyr** [comment]
Hi @arixwap , thank you very much for the pull request!
